import time

print('start of washing')
print('filing water right now...')
time.sleep(5)
print('end of water filling')
print('washing start right now...')
time.sleep(10)
print('end of washing')
print('rinsing right now...')
time.sleep(7)
print('end of rinsing')
print('spinning right now...')
time.sleep(5)
print('end of spinning')
print('start of washing right now...')
print('end of washing')
